{% set name = "code-aster" %}
{% set version = "15.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}_{{ version }}.tar.gz
    url: https://gitlab.com/codeaster/src/-/archive/{{ version }}/src-{{ version }}.tar.gz

build:
  number: 0


requirements:
  host:
    - waf
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libmed==4.1.0 # code aster dependencies
    - scotch
    - metis
    - mumps-include
    - mumps-mpi
    - mumps-seq
    - petsc
    - hdf5
    - numpy
    - glib
    - boost
  run:
    - libmed==4.1.0 # code aster dependencies
    - scotch
    - metis
    - mumps-include
    - mumps-mpi
    - mumps-seq
    - petsc
    - hdf5
    - numpy
    - glib
    - boost

about:
  home: https://www.code-aster.org
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  license_family: GPL
  summary: 'Code_Aster : a finite element solver'
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  doc_url: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande
  dev_url: https://sourceforge.net/projects/codeaster/

extra:
  recipe-maintainers:
    - Krande
